# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapAnalyser
                                 A QGIS plugin
 This tool will help you analyze the map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-10
        copyright            : (C) 2020 by Potemkin D.A., Yakimova O.P
        email                : daniilpot@yandex.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Potemkin D.A., Yakimova O.P'
__date__ = '2020-07-10'
__copyright__ = '(C) 2020 by Potemkin D.A., Yakimova O.P'

import os
from .utils import check


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapAnalyser class from file MapAnalyser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    REQ_PATH = 'requirements.json'
    README_PATH = 'readme_imports.txt'
    # check packages
    directory = os.path.dirname(__file__)
    filename = os.path.join(directory, REQ_PATH)
    check(filename, README_PATH)

    from .map_analyser import MapAnalyserPlugin
    return MapAnalyserPlugin()
