# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TopologicalAndSemanticCharacteristics
                                 A QGIS plugin
 This plugin computes topological and semantic characteristics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-21
        copyright            : (C) 2020 by YSU
        email                : daniilpot@yandex.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'YSU'
__date__ = '2020-08-21'
__copyright__ = '(C) 2020 by YSU'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from PyQt5.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingException,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterVectorLayer,
                       QgsWkbTypes)

from ..utils import tr, raise_exception, write_to_file, define_help_info


class TopologicalAndSemanticCharacteristicsAlgorithm(QgsProcessingAlgorithm):
    """
    This is a class that calculates the topological and
    semantic characteristics of a layer
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    HELP_FILE = 'top_sem_help.txt'

    def __init__(self):
        super().__init__()
        directory = os.path.dirname(__file__)
        file_name = os.path.join(directory, self.HELP_FILE)
        self._shortHelp = define_help_info(file_name)


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                tr('Input layer')
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                tr('Output File'),
                'csv(*.csv)',
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        output = self.parameterAsFileOutput(parameters, self.OUTPUT, context)

        if not layer:
            raise_exception('can\'t get a layer')

        feedback.pushInfo(tr('The algorithm is running'))
        header = [
            'layer',
            'features count',
            'unique values ratios',
            'common length'
        ]
        row = [{
            'layer': layer.name(),
            'features count': self.get_features_count(layer, feedback),
            'unique values ratios': (self.get_formatted_ratios_result(
                self.get_unique_values_ratios(layer, feedback))),
            'common length': self.common_length(layer, feedback)
            }]

        if output:
            feedback.pushInfo(tr('Writing to file'))
            write_to_file(output, header, row, ';')

        return {'Result': row}


    def get_formatted_ratios_result(self, pair):
        """
        This method builds a formatted string of a pair of ratios

        :param pair: Pair of ratios
        """

        if not pair:
            raise_exception("pair is empty")

        first_ratio = '0' if pair[0] == 0.000 else "%.3f" % pair[0]
        second_ratio = '0' if pair[1] == 0.000 else "%.3f" % pair[1]

        return f"{first_ratio}, {second_ratio}"


    def get_features_count(self, layer, feedback):
        """
        This method calculates the number of layer objects

        :param layer: Vector layer
        :param feedback: Feedback from a processing algorithm
        """

        if not layer:
            raise_exception('layer is empty')
        if not feedback:
            raise_exception('feedback is empty')

        data_provider = layer.dataProvider()
        features_count = data_provider.featureCount()
        feedback.setProgress(10)

        return features_count


    def common_length(self, layer, feedback):
        """
        This method calculates the total length of the linear or polygon layer

        :param layer: Vector layer
        :param feedback: Feedback from a processing algorithm
        """

        if not layer:
            raise_exception('layer is empty')
        if not feedback:
            raise_exception('feedback is empty')

        geometry_type = layer.geometryType()

        if geometry_type not in (
            QgsWkbTypes.LineGeometry,
            QgsWkbTypes.PolygonGeometry):

            return 0

        common_length = 0
        total = 30.0 / layer.featureCount() if layer.featureCount() != 0 else 1

        for current, feature in enumerate(layer.getFeatures()):
            if feedback.isCanceled():
                return -1

            common_length += feature.geometry().length()
            feedback.setProgress(int(current * total + 70))

        return round(common_length, 3)


    def get_unique_values_ratios(self, layer, feedback):
        """
        This method calculates the ratio of unique values
        using data provider fields

        :param layer: Vector layer
        :param feedback: Feedback from a processing algorithm
        """

        if not layer:
            raise_exception('layer is empty')
        if not feedback:
            raise_exception('feedback is empty')

        data_provider = layer.dataProvider()
        feature_count = data_provider.featureCount()
        fields = data_provider.fields()
        fields_count = len(fields)

        if feature_count == 0 or fields_count == 0:
            return (0, 0)

        unique_values_count = 0
        total = 60.0 / fields_count

        for i in range(fields_count):
            if feedback.isCanceled():
                return (-1, -1)

            unique_values_count += len(data_provider.uniqueValues(i, feature_count))
            feedback.setProgress(int(i * total + 10))

        unique_values_ratio = round(unique_values_count / feature_count, 3)
        unique_values_ratio_by_fields_count = round(unique_values_ratio / fields_count, 3)

        return (unique_values_ratio, unique_values_ratio_by_fields_count)


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Compute Topological and Sematic characteristics'


    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return tr(self.name())


    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return tr(self.groupId())


    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Map characteristics'


    def shortHelpString(self):
        return self._shortHelp


    def createInstance(self):
        return TopologicalAndSemanticCharacteristicsAlgorithm()
